export const ROUTES = {
    HOME: "/",
    BRAND_OWNERS: "/brand-owners",
    PACKAGING_CONVERTERS: "/packaging-converters",
    CONATCT_US: "/contact",
    ABOUT: "/about-us",
    SERVICES: "/services",
    BLOG: "/blog/",
    PACKARMABLOG: "/packarma-blog/",
    OUR_WORKS: "/work-page/",
    GALLERY: "/gallery",
    APP_and_Business: "/application-and-businness-development",
    BUSINESS_REMODELING: "/business-remodeling",
    CARRERS: "/careers",
    MANAGEMENT_AND_ASSISTANCE: "/mergers-and-acquisitions",
    RESOURCING: "/resourcing",
    SOURCING_EXCELLENCE: "/sourcing-excellence",
    OPERATIONAL_EXCELLENCE: "/operational-excellence",
    VALUE_IMPROVEMENT: "/value-improvement",
    PACKAGING_INNOVATION: "/packaging-innovation",
    SUSTAINABLE_SOLUTION: "/sustainable-solution",
    ARTWORK_AND_GRAPHICS: "/artwork-and-graphics",
    TERMS_AND_CONDITIONS: "/terms-and-conditions",
    PACKARMA_APP: "/packarma-app",
}

export const ADMIN_ROUTES = {
    LOGIN: "/admin",
    BLOGS: "/admin/blogs",
    NEW_BLOG: "/admin/new-blog",
    BLOGS_ID: "/admin/blogs/",
    BLOGS_CREATE: "/admin/blogs/create",
    BLOGS_LAYOUT_1: "/admin/blogs/layout1",
    BLOGS_EDIT_LAYOUT_1: "/admin/blogs/edit/layout1/",
    BLOGS_LAYOUT_2: "/admin/blogs/layout2",
    BLOGS_EDIT_LAYOUT_2: "/admin/blogs/edit/layout2/",
    BLOGS_LAYOUT_3: "/admin/blogs/layout3",
    BLOGS_EDIT_LAYOUT_3: "/admin/blogs/edit/layout3/",

    OUR_WORKS: "/admin/our-works",
    OUR_WORKS_EDIT: "/admin/our-works/edit/our-work/",
    NEW_WORK: "/admin/our-works/new-work",

    CONTACTS: "/admin/contacts",
    CAREERS: "/admin/careers",
    TESTIMONIALS: "/admin/testimonials",
    // PICTURES: "/admin/pictures",

    // packarma new 
    PACKARMA_BLOGS: "/admin/packarma-blog",
    PACKARMA_NEW_BLOG: "/admin/packarma-new-blog",
    PACKARMA_BLOGS_ID: "/admin/packarma-blog/",
    PACKARMA_BLOGS_CREATE: "/admin/packarma-blog/create",
    PACKARMA_BLOGS_LAYOUT_1: "/admin/packarma-blog/layout1",
    PACKARMA_BLOGS_EDIT_LAYOUT_1: "/admin/packarma-blog/edit/layout1/",
    PACKARMA_BLOGS_LAYOUT_2: "/admin/packarma-blog/layout2",
    PACKARMA_BLOGS_EDIT_LAYOUT_2: "/admin/packarma-blog/edit/layout2/",
    PACKARMA_BLOGS_LAYOUT_3: "/admin/packarma-blog/layout3",
    PACKARMA_BLOGS_EDIT_LAYOUT_3: "/admin/packarma-blog/edit/layout3/",

    PACKARMA_TESTIMONIALS: "/admin/packarma-testimonials",

    PACKARMA_OFFERS: "/admin/packarma_offers",
    PACKARMA_VIDEO: "/admin/packarma_video",

}